# Generated by Django 5.0.14 on 2025-12-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0006_remove_telegramuser_is_premium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Название адреса (например: 'Дом', 'Работа')", max_length=100)),
                ('address_text', models.CharField(help_text='Полный адрес доставки', max_length=255)),
                ('latitude', models.FloatField(blank=True, help_text='Широта', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Долгота', null=True)),
                ('entrance', models.CharField(blank=True, help_text='Подъезд', max_length=20)),
                ('floor', models.CharField(blank=True, help_text='Этаж', max_length=20)),
                ('apartment', models.CharField(blank=True, help_text='Квартира/офис', max_length=20)),
                ('intercom', models.CharField(blank=True, help_text='Код домофона', max_length=50)),
                ('comment', models.TextField(blank=True, help_text='Дополнительные комментарии (как пройти и т.д.)')),
                ('is_default', models.BooleanField(default=False, help_text='Адрес по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Пользователь, которому принадлежит адрес', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='telegram_users.telegramuser')),
            ],
            options={
                'verbose_name': 'Адрес пользователя',
                'verbose_name_plural': 'Адреса пользователей',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('user', 'title')},
            },
        ),
    ]
