version: "3.9"

services:
  web:
    build: .
    container_name: sushi_django
    command: gunicorn project_name.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
