# Generated by Django 5.0.14 on 2025-11-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
