# Generated by Django 5.0.14 on 2025-11-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_telegramuser_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='telegram_avatars/'),
        ),
    ]
