# Generated by Django 5.0.14 on 2025-12-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_telegramuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Является ли пользователь администратором'),
        ),
    ]
