# Generated by Django 5.0.14 on 2025-12-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0004_telegramuser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
