# Generated by Django 5.0.14 on 2025-12-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0005_rename_second_name_telegramuser_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='language_code',
        ),
    ]
