# Generated by Django 5.0.14 on 2025-12-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_for_app',
            field=models.BooleanField(default=True, verbose_name='Показывать в Telegram'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_for_qr',
            field=models.BooleanField(default=True, verbose_name='Показывать в QR меню'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_for_app',
            field=models.BooleanField(default=True, verbose_name='Показывать в Telegram'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_for_qr',
            field=models.BooleanField(default=True, verbose_name='Показывать в QR меню'),
        ),
    ]
