# Generated by Django 5.0.14 on 2025-12-08 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_notification'),
        ('orders', '0009_alter_clicktransaction_click_trans_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram ID пользователя')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('notification_type', models.CharField(choices=[('order_approved', 'Заказ одобрен'), ('order_rejected', 'Заказ отклонен'), ('order_cancelled', 'Заказ отменен'), ('cancel_approved', 'Отмена одобрена'), ('cancel_rejected', 'Отмена отклонена'), ('order_status', 'Статус заказа'), ('promo', 'Акция'), ('info', 'Информация')], default='info', max_length=20, verbose_name='Тип')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Уведомление пользователя',
                'verbose_name_plural': 'Уведомления пользователей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telegram_id', '-created_at'], name='content_use_telegra_1481c6_idx'), models.Index(fields=['telegram_id', 'is_read'], name='content_use_telegra_1a022d_idx')],
            },
        ),
    ]
