# Generated by Django 5.0.14 on 2025-11-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_text',
            field=models.CharField(blank=True, help_text='Адрес в свободной форме (улица, дом, подъезд)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')], help_text='Выбор: доставка или самовывоз', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Корзина'), ('new', 'Новый'), ('in_progress', 'В работе'), ('done', 'Доставлен'), ('canceled', 'Отменён')], default='cart', max_length=20),
        ),
    ]
