# Generated by Django 5.0.14 on 2025-12-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_text_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Корзина'), ('new', 'Новый'), ('preparing', 'Готовится'), ('delivering', 'Доставляется'), ('done', 'Доставлен'), ('canceled', 'Отменён')], default='cart', max_length=20),
        ),
    ]
