# Generated by Django 5.0.14 on 2025-12-05 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0003_alter_order_status'),
        ('telegram_users', '0006_remove_telegramuser_is_premium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код промокода (например: SUMMER2024)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Значение скидки (процент или сумма)', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Минимальная сумма заказа для применения промокода', max_digits=10)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Максимальное количество использований (0 = без ограничений)')),
                ('current_uses', models.PositiveIntegerField(default=0, help_text='Текущее количество использований')),
                ('valid_from', models.DateTimeField(help_text='Дата начала действия промокода')),
                ('valid_until', models.DateTimeField(help_text='Дата окончания действия промокода')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли промокод')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма скидки', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_time',
            field=models.CharField(blank=True, help_text="Ориентировочное время готовности (например: '30-40 минут')", max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='canceled_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время отмены', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_canceled',
            field=models.BooleanField(default=False, help_text='Отменен ли товар'),
        ),
        migrations.CreateModel(
            name='OrderItemCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Причина отмены')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Дата и время обработки', null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='orders.orderitem')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Оператор, обработавший запрос', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_cancellations', to='telegram_users.telegramuser')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='telegram_users.telegramuser')),
            ],
            options={
                'verbose_name': 'Запрос на отмену товара',
                'verbose_name_plural': 'Запросы на отмену товаров',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text='Примененный промокод', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название акции', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание акции')),
                ('discount_type', models.CharField(choices=[('percentage', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Значение скидки', max_digits=10)),
                ('valid_from', models.DateTimeField(help_text='Дата начала акции')),
                ('valid_until', models.DateTimeField(help_text='Дата окончания акции')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли акция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(help_text='Товары, участвующие в акции', related_name='promotions', to='menu.product')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-created_at'],
            },
        ),
    ]
