# Generated by Django 5.0.14 on 2025-12-05 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_promocode_alter_order_options_and_more'),
        ('telegram_users', '0006_remove_telegramuser_is_premium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Причина отмены')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Дата и время обработки', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Оператор, обработавший запрос', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_order_cancellations', to='telegram_users.telegramuser')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cancellation_requests', to='telegram_users.telegramuser')),
            ],
            options={
                'verbose_name': 'Запрос на отмену заказа',
                'verbose_name_plural': 'Запросы на отмену заказов',
                'ordering': ['-requested_at'],
            },
        ),
    ]
