# Generated by Django 5.0.14 on 2025-12-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordercancellationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercancellationrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Запрос: Отмена ЗАКАЗА', 'verbose_name_plural': 'Запросы: Отмена ЗАКАЗОВ'},
        ),
        migrations.AlterModelOptions(
            name='orderitemcancellationrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Запрос: Отмена ТОВАРА', 'verbose_name_plural': 'Запросы: Отмена ТОВАРОВ'},
        ),
    ]
