# Generated by Django 5.0.14 on 2025-12-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_paid_at_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные при получении'), ('card', 'Картой курьеру'), ('online', 'Онлайн оплата')], default='cash', help_text='Способ оплаты', max_length=20),
        ),
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_trans_id', models.BigIntegerField(help_text='ID транзакции Click', unique=True)),
                ('merchant_trans_id', models.CharField(help_text='ID заказа (order.id)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма платежа', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('preparing', 'Подготовка'), ('confirmed', 'Подтверждено'), ('canceled', 'Отменено'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('merchant_prepare_id', models.BigIntegerField(blank=True, help_text='ID подготовки транзакции', null=True)),
                ('prepare_time', models.DateTimeField(blank=True, help_text='Время подготовки', null=True)),
                ('complete_time', models.DateTimeField(blank=True, help_text='Время завершения', null=True)),
                ('error_code', models.IntegerField(blank=True, help_text='Код ошибки от Click', null=True)),
                ('error_note', models.TextField(blank=True, help_text='Описание ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='Связанный заказ', on_delete=django.db.models.deletion.CASCADE, related_name='click_transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Click Транзакция',
                'verbose_name_plural': 'Click Транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
