# Generated by Django 5.0.14 on 2025-12-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_payment_method_clicktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicktransaction',
            name='click_trans_id',
            field=models.BigIntegerField(blank=True, help_text='ID транзакции Click (заполняется при callback)', null=True),
        ),
    ]
