# Generated by Django 5.0.14 on 2025-12-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_clicktransaction_click_trans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID транзакции платежной системы (Payme/Click)', max_length=255, null=True),
        ),
    ]
