# Generated by Django 5.0.14 on 2025-12-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default='10:00', help_text='Время открытия')),
                ('closing_time', models.TimeField(default='23:00', help_text='Время закрытия')),
                ('is_manual_mode', models.BooleanField(default=False, help_text='Использовать ручной режим (игнорировать время)')),
                ('is_open_manual', models.BooleanField(default=True, help_text='Открыто ли сейчас (работает только если включен ручной режим)')),
                ('closed_message', models.TextField(default='Ресторан закрыт. Мы работаем с 10:00 до 23:00', help_text='Сообщение, которое видит клиент, когда ресторан закрыт')),
                ('delivery_price', models.DecimalField(decimal_places=2, default=15000, help_text='Стоимость доставки (сум)', max_digits=10)),
            ],
            options={
                'verbose_name': 'Настройки ресторана',
                'verbose_name_plural': 'Настройки ресторана',
            },
        ),
    ]
