# Generated by Django 5.0.14 on 2025-12-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_restaurantsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantsettings',
            name='delivery_price',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Стоимость доставки', max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='delivery_base_km',
            field=models.FloatField(default=2.0, help_text='Базовое расстояние в км (включено в базовую цену)'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='delivery_base_price',
            field=models.DecimalField(decimal_places=2, default=15000, help_text='Базовая стоимость доставки (до X км)', max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='delivery_price_per_km',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Стоимость за каждый дополнительный км', max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='restaurant_lat',
            field=models.FloatField(default=40.1288875, help_text='Широта ресторана (Latitude)'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='restaurant_lng',
            field=models.FloatField(default=67.8244219, help_text='Долгота ресторана (Longitude)'),
        ),
    ]
