# Generated by Django 5.0.14 on 2025-12-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_restaurantsettings_delivery_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_price',
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=15000, help_text='Стоимость доставки (сум) - УСТАРЕЛО, использовать новые поля', max_digits=10),
        ),
    ]
