# Generated by Django 5.0.14 on 2025-12-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_delivery_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Рассчитанная стоимость доставки', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.FloatField(blank=True, help_text='Расстояние доставки в км', null=True),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='delivery_base_km',
            field=models.FloatField(default=2.0, help_text='Базовое расстояние (км), включенное в базовую цену'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='delivery_base_price',
            field=models.DecimalField(decimal_places=2, default=15000, help_text='Базовая цена доставки (до X км)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=15000, help_text='Стоимость доставки (сум) - устаревшее, используйте delivery_base_price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='delivery_price_per_km',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Цена за каждый дополнительный км', max_digits=10),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='restaurant_lat',
            field=models.FloatField(default=41.311081, help_text='Широта ресторана (для расчета расстояния)'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='restaurant_lng',
            field=models.FloatField(default=69.240562, help_text='Долгота ресторана (для расчета расстояния)'),
        ),
    ]
