# Generated by Django 5.0.14 on 2025-12-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_is_for_app_category_is_for_qr_and_more'),
        ('orders', '0015_table_alter_order_delivery_type_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Категория (QR)',
                'verbose_name_plural': 'Категории (QR)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('menu.category',),
        ),
        migrations.CreateModel(
            name='QRProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Товар (QR)',
                'verbose_name_plural': 'Товары (QR)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('menu.product',),
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number'], 'verbose_name': 'Столик', 'verbose_name_plural': 'Столики (QR Меню)'},
        ),
        migrations.AddField(
            model_name='table',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Выберите категории, которые будут доступны по этому QR коду.', related_name='tables', to='menu.category', verbose_name='Категории меню'),
        ),
    ]
