# Generated by Django 5.0.14 on 2025-12-09 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_qrcategory_qrproduct_alter_table_options_and_more'),
        ('qr_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='categories',
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Столик (для заказов в заведении)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='qr_menu.qrtable', verbose_name='Столик (QR)'),
        ),
        migrations.DeleteModel(
            name='QRCategory',
        ),
        migrations.DeleteModel(
            name='QRProduct',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
