# Generated by Django 5.0.14 on 2025-12-09 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_is_for_app_category_is_for_qr_and_more'),
        ('orders', '0017_remove_table_categories_alter_order_table_and_more'),
        ('qr_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='qr_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='qr_menu.qronlyproduct', verbose_name='Товар (QR)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.product'),
        ),
    ]
